import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FaSmileWink } from "react-icons/fa";
import { MdRamenDining } from "react-icons/md";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>HOME | RIMA LAND</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.maintenanceContainer} ${inter.className}`}>
        <p><MdRamenDining /> Currently in Production <MdRamenDining /></p>
        <p>お楽しみに<FaSmileWink /></p>
      </div>

    </>
  )
}
